
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
    name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 150
    time_zone: 'Europe/Moscow'
    unit_system: 'metric'
    currency: RUB
    # Customization file
    customize:
        camera.main_entrance:
            friendly_name: 'Вход в подъезд'
        camera.lobby:
            friendly_name: 'Лобби'
        camera.lobby_elevators:
            friendly_name: 'Лифты'
        camera.parking:
            friendly_name: 'Паркинг'
        camera.parking_elevators:
            friendly_name: 'Лифты (-2 этаж)'
        camera.playground:
            friendly_name: 'Детская площадка'
        camera.courtyard_1_building:
            friendly_name: '1 корпус (улица)'
        camera.courtyard_3_building:
            friendly_name: '3 корпус (улица)'

# Включение поддержки приложения
mobile_app:

# Отслеживание солнца
sun:

# API для предоставления информации о системе и ее компонентах
system_health:

# Text to speech
tts:
  - platform: google_translate

# Manual UI config
lovelace:
    mode: yaml

ffmpeg:
stream:
camera:
  - platform: mjpeg
    name: 'main_entrance'
    mjpeg_url: !secret camera_main_entrance_url

  - platform: mjpeg
    name: 'lobby'
    mjpeg_url: !secret camera_lobby_url

  - platform: mjpeg
    name: 'lobby_elevators'
    mjpeg_url: !secret camera_lobby_elevators_url

  - platform: mjpeg
    name: 'parking'
    mjpeg_url: !secret camera_parking_url

  - platform: mjpeg
    name: 'parking_elevators'
    mjpeg_url: !secret camera_parking_elevators_url

  - platform: mjpeg
    name: 'playground'
    mjpeg_url: !secret camera_playground_url

  - platform: mjpeg
    name: 'courtyard_1_building'
    mjpeg_url: !secret camera_courtyard_1_building_url

  - platform: mjpeg
    name: 'courtyard_3_building'
    mjpeg_url: !secret camera_courtyard_3_building_url
    
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

