# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Базовая информация
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 150
  time_zone: "Europe/Moscow"
  unit_system: "metric"
  currency: RUB
  customize: !include_dir_merge_named includes/customize/

# Включение поддержки приложения
mobile_app:

# Отслеживание солнца
sun:

# API для предоставления информации о системе и ее компонентах
system_health:

# Роутер Asus
asuswrt:
  host: !secret asus_router_ip
  protocol: ssh
  username: !secret asus_router_username
  ssh_key: !secret asus_router_id_rsa
  mode: router
  interface: vlan2
  sensors:
    - devices
    - upload_speed
    - download_speed

# Text to speech
tts:
  - platform: google_translate

# Ручное управление интерфейсом
lovelace:
  mode: yaml

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Камеры наблюдения
ffmpeg:
stream:
camera: !include includes/cameras.yaml

# Датчики
sensor: !include_dir_merge_list includes/sensors/

# База данных
recorder: !include includes/recorder.yaml

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml

# Телевизоры, проекторы, колонки
media_player: !include includes/media_players.yaml

# Освещение Yeelight
yeelight: !include includes/yeelight.yaml

logger:
  default: info
  # logs:
  # homeassistant.components.rest: debug
