
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Базовая информация
homeassistant:
    name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 150
    time_zone: 'Europe/Moscow'
    unit_system: 'metric'
    currency: RUB
    customize: !include_dir_merge_named customize/

# Включение поддержки приложения
mobile_app:

# Отслеживание солнца
sun:

# API для предоставления информации о системе и ее компонентах
system_health:

# Text to speech
tts:
  - platform: google_translate

# Ручное управление интерфейсом
lovelace:
    mode: yaml

# Камеры наблюдения
ffmpeg:
stream:
camera: !include cameras.yaml

# Датчики
sensor: !include sensors.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Телевизоры, проекторы, колонки
media_player: !include media_players.yaml
