title: 'Home Assistant'
views:
  - title: 'Главная'
    id: mian
    icon: mdi:memory
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            name: 'Загрузка CPU'
            unit: '%'
            min: 0
            max: 100
            entity: sensor.processor_use
            severity:
                green: 0
                yellow: 60
                red: 85
                
      - type: vertical-stack
        cards:
          - type: gauge
            name: 'Загрузка RAM'
            unit: '%'
            min: 0
            max: 100
            entity: sensor.memory_use_percent
            severity:
                green: 0
                yellow: 60
                red: 85
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.memory_use
                name: 'Используется'
              - type: sensor
                entity: sensor.memory_free
                name: 'Свободно'
                
      - type: vertical-stack
        cards:
          - type: gauge
            name: 'Загрузка диска'
            unit: '%'
            min: 0
            max: 100
            entity: sensor.disk_use_percent
            severity:
                green: 0
                yellow: 60
                red: 85
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.disk_use
                name: 'Занято'
              - type: sensor
                entity: sensor.disk_free
                name: 'Свободно'


  - title: 'Камеры'
    id: cameras
    cards:
      - type: grid
        title: 'Подъезд'
        columns: 2
        square: false
        cards:
          - type: picture-entity
            name: 'Вход в подъезд'
            camera_image: camera.main_entrance
            camera_view: live
            entity: sensor.time_date
            show_state: true
    
          - type: picture-entity
            name: 'Лобби'
            camera_image: camera.lobby
            camera_view: live
            entity: sensor.time_date
            show_state: true
            
          - type: picture-entity
            name: 'Лифты'
            camera_image: camera.lobby_elevators
            camera_view: live
            entity: sensor.time_date
            show_state: true

      - type: grid
        title: 'Паркинг'
        columns: 2
        square: false
        cards:
            - type: picture-entity
              name: 'Лифты (-2 этаж)'
              camera_image: camera.parking_elevators
              camera_view: auto
              entity: sensor.time_date
              show_state: true
              
            - type: picture-entity
              name: Паркинг
              camera_image: camera.parking
              camera_view: auto
              entity: sensor.time_date
              show_state: true
              
      - type: grid
        title: 'Двор'
        columns: 2
        square: false
        cards:
          
        - type: picture-entity
          name: '3 корпус'
          camera_image: camera.courtyard_3_building
          camera_view: auto
          entity: sensor.time_date
          show_state: true
          
        - type: picture-entity
          name: '1 корпус'
          camera_image: camera.courtyard_1_building
          camera_view: auto
          entity: sensor.time_date
          show_state: true
          
        - type: picture-entity
          name: 'Детская площадка'
          camera_image: camera.playground
          camera_view: auto
          entity: sensor.time_date
          show_state: true
          
