# Мониторинг системы
- platform: systemmonitor
  resources:
    # Использование процессора в %
    - type: processor_use
    # Дата и время последней перезагрузки
    - type: last_boot
    # Использование оперативной памяти в %
    - type: memory_use_percent
    # Используемая оперативная память в МБ
    - type: memory_use
    # Свободная оперативная память в МБ
    - type: memory_free
    # Занятое место на диске в %
    - type: disk_use_percent
      arg: /
    # Занятое место на диске в ГБ
    - type: disk_use
      arg: /
    # Свободное место на диске в ГБ
    - type: disk_free
      arg: /

# Размер базы данных
- platform: sql
  db_url: !secret maria_db_url
  queries:
    - name: maria_db_size
      query: "SELECT table_schema 'database', Round(Sum(data_length + index_length) / (1024 * 1024), 2) 'value' FROM information_schema.tables WHERE table_schema='homeassistant' GROUP BY table_schema;"
      column: "value"
      unit_of_measurement: MB

# Дата и время в Европейском формате
- platform: template
  sensors:
    formated_date_time:
      friendly_name: "Дата и время"
      value_template: "{{ now().timestamp() | timestamp_custom('%d.%m.%y %H:%M') }}"
      icon_template: mdi:calendar-clock

# Дата и время
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "time_date"

# Дата в Европейском формате
- platform: template
  sensors:
    formated_date:
      friendly_name: "Дата"
      value_template: "{{ now().timestamp() | timestamp_custom('%d.%m.%Y') }}"
      icon_template: mdi:calendar-clock

# Получение показаний электросчётчика
- platform: rest
  resource: !secret domyland_electricity_url
  method: GET
  headers:
    Authorization: !secret domyland_tooken
    AppName: !secret domyland_app_name
    AppVersion: !secret domyland_app_version
    buildingId: !secret domyland_building_id
    placeId: !secret domyland_place_id
  verify_ssl: false
  value_template: "{{ value_json['success'] }}"
  json_attributes_path: "$.['data']['items'][0]"
  json_attributes:
    - meteringDeviceNumber
    - submittedAt
    - createdAt
    - lastCalibrationDate
    - meteringDeviceNextCalibrationDate
    - value1
    - delta1
    - value2
    - delta2
    - value3
    - delta3
  name: domyland_electricity
  # 12 часов
  scan_interval: 43200

# Датчики показаний электросчётчика
- platform: template
  sensors:
    domyland_electricity_gauge_number:
      friendly_name: "Номер электросчётчика"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'meteringDeviceNumber') }}"
    domyland_electricity_last_submit:
      friendly_name: "Дата последней передачи показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_electricity', 'submittedAt') }}"
    domyland_electricity_last_check:
      friendly_name: "Дата последнего обновления показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_electricity', 'createdAt') }}"
    domyland_heating_last_calibration_date:
      friendly_name: "Дата последней калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'lastCalibrationDate') }}"
    domyland_heating_next_calibration_date:
      friendly_name: "Дата следующей калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'meteringDeviceNextCalibrationDate') }}"
    domyland_electricity_t1_value:
      friendly_name: "Электричество T1 (пик)"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value1') | float }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t1_delta:
      friendly_name: "Электричество T1 (пик) изменение"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta1') | float }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t2_value:
      friendly_name: "Электричество T2 (ночь)"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value2') | float }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t2_delta:
      friendly_name: "Электричество T2 (ночь) изменение"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta2') | float }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t3_value:
      friendly_name: "Электричество T3 (п/пик)"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value3') | float }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t3_delta:
      friendly_name: "Электричество T3 (п/пик) изменение"
      icon_template: mdi:transmission-tower
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta3') | float }}"
      unit_of_measurement: "kWH"

# Получение показаний теплосчётчиков
- platform: rest
  name: domyland_heating
  resource: !secret domyland_heating_url
  method: GET
  headers:
    Authorization: !secret domyland_tooken
    AppName: !secret domyland_app_name
    AppVersion: !secret domyland_app_version
    buildingId: !secret domyland_building_id
    placeId: !secret domyland_place_id
  verify_ssl: false
  value_template: "{{ value_json['success'] }}"
  json_attributes_path: "$.['data']['items'][0]"
  json_attributes:
    - meteringDeviceNumber
    - submittedAt
    - createdAt
    - lastCalibrationDate
    - meteringDeviceNextCalibrationDate
    - value1
    - delta1
  # 12 часов
  scan_interval: 43200

  # Датчики показаний теплосчётчиков
- platform: template
  sensors:
    domyland_heating_gauge_number:
      friendly_name: "Номер теплосчётчика"
      icon_template: mdi:radiator
      value_template: "{{ state_attr('sensor.domyland_heating', 'meteringDeviceNumber') }}"
    domyland_heating_last_submit:
      friendly_name: "Дата последней передачи показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'submittedAt') }}"
    domyland_heating_last_check:
      friendly_name: "Дата последнего обновления показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'createdAt') }}"
    domyland_heating_last_calibration_date:
      friendly_name: "Дата последней калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'lastCalibrationDate') }}"
    domyland_heating_next_calibration_date:
      friendly_name: "Дата следующей калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_heating', 'meteringDeviceNextCalibrationDate') }}"
    domyland_heating_value:
      friendly_name: "Показания теплосчётчика"
      icon_template: mdi:radiator
      value_template: "{{ state_attr('sensor.domyland_heating', 'value1') | float }}"
      unit_of_measurement: "GCal"
    domyland_heating_delta:
      friendly_name: "Изменение показаний теплосчётчика"
      icon_template: mdi:radiator
      value_template: "{{ state_attr('sensor.domyland_heating', 'delta1') | float }}"
      unit_of_measurement: "GCal"

# Получение показаний воды
- platform: rest
  name: domyland_water
  resource: !secret domyland_water_url
  method: GET
  headers:
    Authorization: !secret domyland_tooken
    AppName: !secret domyland_app_name
    AppVersion: !secret domyland_app_version
    buildingId: !secret domyland_building_id
    placeId: !secret domyland_place_id
  verify_ssl: false
  value_template: "{{ value_json['success'] }}"
  json_attributes_path: "$.['data']"
  json_attributes:
    - items
  # 12 часов
  scan_interval: 43200

  # Датчики показаний воды
- platform: template
  sensors:
    # Холодная вода
    domyland_water_cold_gauge_number:
      friendly_name: "Номер счётчика"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].meteringDeviceNumber }}"
    domyland_water_cold_last_submit:
      friendly_name: "Дата последней передачи показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].submittedAt }}"
    domyland_water_cold_last_check:
      friendly_name: "Дата последнего обновления показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].createdAt }}"
    domyland_water_cold_last_calibration_date:
      friendly_name: "Дата последней калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].lastCalibrationDate }}"
    domyland_water_cold_next_calibration_date:
      friendly_name: "Дата следующей калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].meteringDeviceNextCalibrationDate }}"
    domyland_water_cold_value:
      friendly_name: "Холодная вода (показания)"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].value1 | float }}"
      unit_of_measurement: "m³"
    domyland_water_cold_delta:
      friendly_name: "Холодная вода (изменение)"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][0].delta1 | float }}"
      unit_of_measurement: "m³"
    # Горячая вода
    domyland_water_hot_gauge_number:
      friendly_name: "Номер счётчика"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].meteringDeviceNumber }}"
    domyland_water_hot_last_submit:
      friendly_name: "Дата последней передачи показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].submittedAt }}"
    domyland_water_hot_last_check:
      friendly_name: "Дата последнего обновления показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].createdAt }}"
    domyland_water_hot_last_calibration_date:
      friendly_name: "Дата последней калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].lastCalibrationDate }}"
    domyland_water_hot_next_calibration_date:
      friendly_name: "Дата следующей калибровки счётчика"
      icon_template: mdi:calendar-clock
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].meteringDeviceNextCalibrationDate }}"
    domyland_water_hot_value:
      friendly_name: "Горячая вода (показания)"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].value1 | float }}"
      unit_of_measurement: "m³"
    domyland_water_hot_delta:
      friendly_name: "Горячая вода (изменение)"
      icon_template: mdi:water-pump
      value_template: "{{ states.sensor.domyland_water.attributes['items'][1].delta1 | float }}"
      unit_of_measurement: "m³"
    # Водоотведение
    domyland_water_drainage_value:
      friendly_name: "Водоотведение (показания)"
      icon_template: mdi:water-pump
      value_template: "{{ (states.sensor.domyland_water.attributes['items'][0].value1 | float) + (states.sensor.domyland_water.attributes['items'][1].value1 | float) }}"
      unit_of_measurement: "m³"
    domyland_water_drainage_delta:
      friendly_name: "Водоотведение (изменение)"
      icon_template: mdi:water-pump
      value_template: "{{ (states.sensor.domyland_water.attributes['items'][0].delta1 | float) + (states.sensor.domyland_water.attributes['items'][1].delta1 | float) }}"
      unit_of_measurement: "m³"
