# Мониторинг системы
- platform: systemmonitor
  resources:
    # Использование процессора в %
    - type: processor_use
    # Дата и время последней перезагрузки
    - type: last_boot
    # Использование оперативной памяти в %
    - type: memory_use_percent
    # Используемая оперативная память в МБ
    - type: memory_use
    # Свободная оперативная память в МБ
    - type: memory_free
    # Занятое место на диске в %
    - type: disk_use_percent
      arg: /
    # Занятое место на диске в ГБ
    - type: disk_use
      arg: /
    # Свободное место на диске в ГБ
    - type: disk_free
      arg: /

# Размер базы данных
- platform: sql
  db_url: !secret maria_db_url
  queries:
    - name: maria_db_size
      query: "SELECT table_schema 'database', Round(Sum(data_length + index_length) / (1024 * 1024), 2) 'value' FROM information_schema.tables WHERE table_schema='homeassistant' GROUP BY table_schema;"
      column: "value"
      unit_of_measurement: MB

# Дата и время в Европейском формате
- platform: template
  sensors:
    formated_date_time:
      friendly_name: "Дата и время"
      value_template: "{{ now().timestamp() | timestamp_custom('%d.%m.%y %H:%M') }}"
      icon_template: mdi:calendar-clock

# Дата и время
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "time_date"

# Дата в Европейском формате
- platform: template
  sensors:
    formated_date:
      friendly_name: "Дата"
      value_template: "{{ now().timestamp() | timestamp_custom('%d.%m.%Y') }}"
      icon_template: mdi:calendar-clock

# Получение показаний электросчётчика
- platform: rest
  resource: !secret domyland_electricity_url
  method: GET
  headers:
    Authorization: !secret domyland_tooken
    AppName: !secret domyland_app_name
    AppVersion: !secret domyland_app_version
    buildingId: !secret domyland_building_id
    placeId: !secret domyland_place_id
  verify_ssl: false
  value_template: "{{ value_json['success'] }}"
  json_attributes_path: "$.['data']['items'][0]"
  json_attributes:
    - meteringDeviceNumber
    - submittedAt
    - createdAt
    - value1
    - delta1
    - value2
    - delta2
    - value3
    - delta3
  name: domyland_electricity
  scan_interval: 3600

# Датчики показаний электросчётчика
- platform: template
  sensors:
    domyland_electricity_gauge_number:
      friendly_name: "Номер электросчётчика"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'meteringDeviceNumber') }}"
    domyland_electricity_last_submit:
      friendly_name: "Дата последней передачи показаний"
      icon_template: mdi:calendar-clock
      value_template: "{{ state_attr('sensor.domyland_electricity', 'submittedAt') }}"
    domyland_electricity_last_check:
      friendly_name: "Дата последнего обновления показаний"
      value_template: "{{ state_attr('sensor.domyland_electricity', 'createdAt') }}"
    domyland_electricity_t1_value:
      friendly_name: "Электричество T1 (пик)"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value1') }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t1_delta:
      friendly_name: "Электричество T1 (пик) изменение"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta1') }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t2_value:
      friendly_name: "Электричество T2 (ночь)"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value2') }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t2_delta:
      friendly_name: "Электричество T2 (ночь) изменение"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta2') }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t3_value:
      friendly_name: "Электричество T3 (п/пик)"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'value3') }}"
      unit_of_measurement: "kWH"
    domyland_electricity_t3_delta:
      friendly_name: "Электричество T3 (п/пик) изменение"
      icon_template: mdi:meter-electric-outline
      value_template: "{{ state_attr('sensor.domyland_electricity', 'delta3') }}"
      unit_of_measurement: "kWH"
